### ISSUE TITLE
Non-existent service breaks template 

### ISSUE THREAD

**Issue by jgreat** [janeczku/rancher-template#1]
I'm trying to create dynamic haproxy configs and everything works great, unless I'm missing a service. 

When I try to use a `with service "X"` statement and the service X doesn't exist, rancher-template errors. I would expect it to return empty or nil so the `else` statement would take effect.

Is there a better way to do this?

My template: haproxy.tmpl
```
backend bk_web
  description "http://web:8400/_status"
  option httpchk GET "http://web:8400/_status"
{{ with service "web.web" }}
{{ range .Containers }}  server {{.Name}} {{.Address}}:8400 check inter 10s{{ end }}
{{ else }}  server none 127.0.0.1:80 disabled {{ end }}
```

The error:
```
level=fatal msg="Executing template: template: haproxy.tmpl:102:8: executing \"haproxy.tmpl\" at <service \"web...>: error calling service: (service) could not find 'web.web'"
```

**Comment by janeczku** [comment]
@jgreat Thanks for capturing this. I agree, it should return an empty service object for non-existing services.

**Comment by janeczku** [comment]
Fixed in https://github.com/janeczku/rancher-template/commit/60d97cd21776a956aca3bce480a4b3c3ed4340e3

**Comment by jgreat** [comment]
Confirmed, Thanks
